# This is an example configuration file for Spot.  It is not used!

/**:
  ros__parameters:
    rates:
      # loop_frequency is the frequency of the loop which publishes messages
      loop_frequency: 400.0
      # These are desired frequencies. You should not expect to receive messages at exactly the specified frequency. For
      # higher frequencies, you will need to modify the loop frequency and the rates below.
      robot_state: 10.0
      metrics: 0.04
      lease: 1.0
      front_image: 10.0
      side_image: 10.0
      rear_image: 10.0
      point_cloud: 10.0
      # hand_image: 2.0
      feedback: 100.0
      mobility_params: 100.0
      check_subscribers: 100.0
    auto_claim: True
    auto_power_on: True
    auto_stand: True
    start_estop: False
    deadzone: 0.5
    estop_timeout: 9.0
    cmd_duration: 0.25 #0.125 # think this one is important, but might by set in youre own packages
    username: "user"
    password: "rtbtnp6wxwqh"
    hostname: "192.168.80.3"
    rgb_cameras: False
    initialize_spot_cam: False
    preferred_odom_frame: "odom"
    #"192.168.80.3"
    #"10.0.0.3" mono8
